name: Build (Win/Mac/Linux) and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  # Подставляем значения из Settings → Actions → Variables/Secrets
  BACKEND_BASE_URL: ${{ vars.BACKEND_BASE_URL }}
  INSTALL_DIR_NAME: ${{ vars.INSTALL_DIR_NAME }}
  APP_KEY: ${{ secrets.APP_KEY }}
  CSC_IDENTITY_AUTO_DISCOVERY: 'false'

jobs:
  build:
    name: Build ${{ matrix.name }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: Windows
            target: '--win nsis portable --x64'
            artifact: artifacts-win
          - os: macos-latest
            name: macOS
            target: '--mac dmg'
            artifact: artifacts-mac
          - os: ubuntu-latest
            name: Linux
            target: '--linux AppImage'
            artifact: artifacts-linux
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (vite + electron)
        run: npm run build

      - name: Package ${{ matrix.name }} (${{ matrix.target }})
        run: npx electron-builder ${{ matrix.target }} -p always

      - name: List dist
        run: |
          echo "Dist:" && ls -al dist || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            dist/**
          if-no-files-found: error

  # Доп. джоба релиза больше не нужна — electron-builder публикует напрямую

